CREATE PROCEDURE [dbo].[GetProjectSelectList] 
AS
BEGIN
	SET NOCOUNT ON;  
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  
	SET LOCK_TIMEOUT 20000;  

	BEGIN TRY  
		SELECT Id, Subject FROM Project
	END TRY

	BEGIN CATCH
	END CATCH
END