ALTER PROCEDURE [dbo].[GetUserList] 
AS
BEGIN
	SET NOCOUNT ON;  
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  
	SET LOCK_TIMEOUT 20000;  

	BEGIN TRY  
		SELECT UserId, Name, Email, Mobile, Org, ImageUrl FROM Users
	END TRY

	BEGIN CATCH
	END CATCH
END