CREATE PROCEDURE [dbo].[GetUsers] 
AS
BEGIN
	SET NOCOUNT ON;  
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;  
	SET LOCK_TIMEOUT 20000;  

	BEGIN TRY  		
		SELECT [UserId], [Name]
		FROM [Jira].[dbo].[Users]
	END TRY

	BEGIN CATCH
	END CATCH
END